name: Build Develop Push
on:
  push:
    branches:
      - 'dnx'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: 
      name: develop
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref:  main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo "::set-output name=tag::$(git rev-parse --short $GITHUB_SHA)"
      - name: Login to ECR
        uses: docker/login-action@v1 
        with:
          registry: 869898323958.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.DNX_AK }}
          password: ${{ secrets.DNX_SK }} 
      - name: Build and push - Rapidpro Image
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: 869898323958.dkr.ecr.us-east-1.amazonaws.com/rp-archiver:${{ steps.vars.outputs.tag }}
          no-cache: true